files:
  - source: /BetterErProspecting/BetterErProspecting/assets/bettererprospecting/lang/en.json
    translation: /BetterErProspecting/BetterErProspecting/assets/bettererprospecting/lang/%two_letters_code%.json
